version: '3.8'
services:
  db:
    image: postgres:16.3
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=aethradb
      - POSTGRES_USER=sellinios
      - POSTGRES_PASSWORD=4c3548afe4d70c234800b360bd26736c
    command: >
      bash -c "
        echo 'CREATE DATABASE aethradb;' > /docker-entrypoint-initdb.d/init.sql &&
        echo 'CREATE USER sellinios WITH PASSWORD ''0b76dfbfb2cc4fd6cd866c769d75ac65'';' >> /docker-entrypoint-initdb.d/init.sql &&
        echo 'GRANT ALL PRIVILEGES ON DATABASE aethradb TO sellinios;' >> /docker-entrypoint-initdb.d/init.sql &&
        docker-entrypoint.sh postgres
      "
    deploy:
      replicas: 1
    networks:
      - aethra_network

  backend:
    image: aethra_backend:latest
    deploy:
      replicas: 2
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings.production
      - DJANGO_SECRET_KEY=492d5455ab955c17a895f765ecad17256c18cb95584613265bce6701e91ef9c3
      - DJANGO_DEBUG=False
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,kairos.gr,www.kairos.gr
      - POSTGRES_DB=aethradb
      - POSTGRES_USER=sellinios
      - POSTGRES_PASSWORD=4c3548afe4d70c234800b360bd26736c
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - CORS_ALLOWED_ORIGINS=https://kairos.gr,https://www.kairos.gr
    volumes:
      - static_volume:/app/staticfiles
    networks:
      - aethra_network
    depends_on:
      - db

  frontend:
    image: aethra_frontend:latest
    deploy:
      replicas: 2
    volumes:
      - ./frontend-nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/usr/share/nginx/html/static
    networks:
      - aethra_network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - static_volume:/usr/share/nginx/html/static
    deploy:
      replicas: 1
    networks:
      - aethra_network
    depends_on:
      - backend
      - frontend

networks:
  aethra_network:
    name: aethra_network
    driver: overlay

volumes:
  postgres_data:
  static_volume: