version: '3.8'
services:
  db:
    image: postgres:16.3
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=aethradb
      - POSTGRES_USER=sellinios
      - POSTGRES_PASSWORD=faidra123!@#
    deploy:
      replicas: 1
    networks:
      - aethra_network

  backend:
    image: aethra_backend:latest
    deploy:
      replicas: 2
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings.production
      - DJANGO_SECRET_KEY=m*)@-#%@a!w(y_w#k!@$p81jzg=3nir#(t(!0i7fmw)!v0fdf3
      - DJANGO_DEBUG=False
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,kairos.gr,www.kairos.gr
      - POSTGRES_DB=aethradb
      - POSTGRES_USER=sellinios
      - POSTGRES_PASSWORD=faidra123!@#
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - CORS_ALLOWED_ORIGINS=https://kairos.gr,https://www.kairos.gr
    volumes:
      - static_volume:/app/staticfiles
    networks:
      - aethra_network
    depends_on:
      - db

  frontend:
    image: aethra_frontend:latest
    deploy:
      replicas: 2
    networks:
      - aethra_network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - static_volume:/app/staticfiles
    deploy:
      replicas: 1
    networks:
      - aethra_network
    depends_on:
      - backend
      - frontend

networks:
  aethra_network:
    name: aethra_network
    driver: overlay

volumes:
  postgres_data:
  static_volume: